#
#    This is a snapcraft build script.
#    Copyright (C) 2021-2022 Jintao Yang <yjt950840@outlook.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#    snapcraft.yaml:
#       snapcraft script.
#       build snap package on Linux.
#

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: serialporttool
version: '20.22.05' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Cross-platform serial debug tool. # 79 char long summary
description: |
  A simple command-line Cross-platform serial debug tool, created by Joker2770< https://github.com/Joker2770/SerialPortTool.git >.

  **For hardware access of serial port, you would better install with '--devmode'. e.g.**
     `sudo snap install --devmode serialporttool --beta`

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  serialporttool:
    command: SerialPortTool
    plugs:
      - serial-port
      - raw-usb

parts:
  serialporttool:
    # See 'snapcraft plugins'
    plugin: cmake
    source: "https://github.com/Joker2770/SerialPortTool.git"
    # source: ../
    source-depth: 1
    source-branch: master
    source-type: git
    build-packages:
     - gcc
     - g++
     - cmake
     - make

   # publish:
    # plugin: dump
    # organize:
        # ./bin/SerialPortTool: bin/SerialPortTool
     
