# After registering a name on build.snapcraft.io, commit an uncommented line:
name: serialporttool
version: '20.22.05' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Cross-platform serial debug tool. # 79 char long summary
description: |
  A simple command-line Cross-platform serial debug tool, created by Joker2770< https://github.com/Joker2770/SerialPortTool >.

  **For serial port hardware access, you would better install with '--devmoe'. e.g.**
     `sudo snap install --devmode serialporttool --beta`

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  serialporttool:
    command: SerialPortTool
    plugs:
      - serial-port
      - raw-usb

parts:
  serialporttool:
    # See 'snapcraft plugins'
    plugin: cmake
    source: "https://github.com/Joker2770/SerialPortTool.git"
    # source: ../
    source-depth: 1
    source-branch: master
    source-type: git
    build-packages:
     - gcc
     - g++
     - cmake
     - make

   # publish:
    # plugin: dump
    # organize:
        # ./bin/SerialPortTool: bin/SerialPortTool
     
